yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"


urlpatterns = [
    path('', views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path("follow", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permisson_denied"


urlpatterns = [
    path('', include('posts.urls', namespace="posts")),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

TEXT_LIMIT = 15


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='Путь'
    )
    description = models.TextField(
        max_length=400,
        verbose_name='Описание'
    )

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группу'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        max_length=400,
        help_text='Введите текст поста',
        verbose_name='Текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:TEXT_LIMIT]


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments"
    )
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:TEXT_LIMIT]


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_follower_following"
            )
        ]

    def __str__(self):
        return f"{self.user.username} подписан на {self.author.username}"

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", "image"]
        labels = {'text': 'Текст', 'group': 'Группа', 'image': 'Картинка'}
        help_texts = {'text': 'Введите текст публикации',
                      'group': 'Выберите группу', }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

yatube/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow
from .utils import get_paginator_helper


@cache_page(20, cache='default', key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    page_obj = get_paginator_helper(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = get_paginator_helper(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = get_paginator_helper(request, post_list)
    following = request.user.is_authenticated and Follow.objects.filter(
        author=author,
        user=request.user).exists()
    context = {
        "page_obj": page_obj,
        "author": author,
        "following": following
    }
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments_for_post = post.comments.all()
    context = {
        "post": post,
        "form": form,
        "comments": comments_for_post
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author.username)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect("posts:post_detail", post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {
        "form": form,
        "post_id": post_id,
        "is_edit": True,
    }
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user
    ).select_related("group")
    page_obj = get_paginator_helper(request, post_list)
    context = {"page_obj": page_obj}
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактировать
{% else %}
Новая запись
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
<body>
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
              Редактировать пост
              {% else %}
              Новый пост
              {% endif %}
            </div>
            <div class="card-body">
              {% include 'includes/forms/fields_if_form_errors.html' %}
              <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
              <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'includes/forms/fields_if_form_errors.html' %}
                <div class="form-group row my-3 p-3">
                  {% for field in form %}
                  <label for="id_text">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:"form-control" }}
                  <small>
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                  </small>
                  {% endfor %}
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                    Сохранить
                    {% else %}
                    Опубликовать
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
{% include 'posts/includes/post_card.html' with show_group_link=True show_profile_link=True%}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
</div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description|linebreaksbr }}
  </p>
  <br>
        {% for post in page_obj %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {% include 'posts/includes/post_card.html' with show_profile_link=True%}
        {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% include 'posts/includes/post_card.html' with show_group_link=True show_profile_link=True%}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Все посты пользователя{% endblock %}
{% block content %} 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}  
            <li class="list-group-item">
              Группа: {{post.group}}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                Все записи группы
              {% endif %}  
              </a>
            </li>
            <li class="list-group-item">
              Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{count_posts}}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                Все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
            {% if request.user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post_id=post.pk %}">
            Редактировать запись
            {% endif %}
            </a>
        </article>
        {% include 'includes/forms/comments.html' %}
      </div>
      {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %} 
     <div class="mb-5">       
        <h1>Все посты пользователя {{author}} </h1>
        <h3>Всего постов: {{count_posts}} </h3>   
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
           {% for post in page_obj %}
           {% include 'posts/includes/post_card.html' with show_group_link=True %} 
           {% endfor %}
           {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
           <img class="card-img my-2" src="{{ im.url }}">
           {% endthumbnail %}
          {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}