yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_change_form', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change_done',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password_reset_form', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset_confirm',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset_complete',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permisson_denied"


urlpatterns = [
    path('', include('posts.urls', namespace="posts")),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("posts:index")
    template_name = "users/signup.html"

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/forms/fields_if_form_errors.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
            {% include 'includes/forms/fields_in_post_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                Забыли пароль?
            </a>
          </div>
          </form>
        </div> 
      </div> 
    </div> 
</div> 
{% endblock %}

yatube/templates/users/password_change.html
{% extends "base.html" %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Смена пароля
          </div>
          <div class="card-body">
            {% include 'posts/includes/forms/fields_if_form_errors.html' %}
            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
              {% csrf_token %}
              {% include 'posts/includes/forms/fields_in_post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сменить пароль
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
{% endblock %}    

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% if validlink %}
    {% include 'posts/includes/forms/fields_if_form_errors.html' %}
    <form method="post"
      {% if action_url %}
        action="{% url action_url %}"
      {% endif %}
    >
      {% csrf_token %}
      {% include 'posts/includes/forms/fields_in_post_form.html' %}
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Назначить новый пароль
        </button>
      </div>
    </form>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> 
        </div>
      </div>
    </div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{%endblock%}      

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            {% include 'posts/includes/forms/fields_if_form_errors.html' %}
            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
              {% csrf_token %}
              {% include 'posts/includes/forms/fields_in_post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
    </div> 
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% load user_filters %}
            {% include 'includes/forms/fields_if_form_errors.html' %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% include 'includes/forms/fields_in_post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
  </div> 
{% endblock %}